name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build_on_unix:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./config --prefix=/tmp/openssl
    - name: make
      run: make
    - name: make test
      run: make test
  build_on_windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: perl Configure VC-WIN64A 
      - name: make
        run: nmake
      - name: make test
        run: nmake test
