name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build_on_unix:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./config --prefix=/tmp/openssl
    - name: make
      run: make
    - name: make test
      run: make test
  build_on_windows:
    runs-on: windows-2019
    steps:
      - name: install nasm
        run: |
             Get-ChildItem "c:\Program Files (x86)\Microsoft Visual Studio\2019\Community" -Recurse nmake.exe
             choco install -y -d nasm
             dir "c:\program Files"
             echo "::add-path::C:\Program Files\NASM"
      - name: print path
        run: $env:path      
      - uses: actions/checkout@v2
      - name: configure
        run: perl Configure VC-WIN64A 
      - name: make
        run: |
              "c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
              nmake
      - name: make test
        run: nmake test
